steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/sentence-splitter/app:$COMMIT_SHA'
      - '-t'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/sentence-splitter/app:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - '--all-tags'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/sentence-splitter/app'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - sentence-splitter
      - '--image=asia-northeast3-docker.pkg.dev/$PROJECT_ID/sentence-splitter/app:$COMMIT_SHA'
      - '--region=asia-northeast3'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8001'
      - '--memory=2Gi'
      - '--cpu=2'

images:
  - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/sentence-splitter/app:$COMMIT_SHA'
  - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/sentence-splitter/app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
